//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public int car_id { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> year_manufacture { get; set; }
        public string number_plate { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public string image { get; set; }
        public Nullable<int> is_delete { get; set; }
        public Nullable<int> car_status_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<int> model_id { get; set; }
        public Nullable<int> car_type_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> vehicle_registration_id { get; set; }
        public Nullable<int> count_journeys { get; set; }
    }
}
