//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADDDA_APPEntities : DbContext
    {
        public ADDDA_APPEntities()
            : base("name=ADDDA_APPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<booking> booking { get; set; }
        public virtual DbSet<booking_status> booking_status { get; set; }
        public virtual DbSet<brand> brand { get; set; }
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<car_status> car_status { get; set; }
        public virtual DbSet<car_type> car_type { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<favorite_car> favorite_car { get; set; }
        public virtual DbSet<feeback> feeback { get; set; }
        public virtual DbSet<model> model { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vehicle_registration> vehicle_registration { get; set; }
    }
}
