//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_registration
    {
        public int vehicle_registration_id { get; set; }
        public string vehicle_registration_image { get; set; }
        public string vehicle_inspection_image { get; set; }
    }
}
